name: .NET

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 5.0.x
    - name: Restore dependencies
      run: dotnet restore
    - name: Build
      run: dotnet build --no-restore
    - name: Test
      run: dotnet test --no-build --verbosity normal
    - name: Publish web app
      working-directory: ./Doppler.REST
      run: dotnet publish -c Release --runtime linux-x64 --self-contained false
    - name: Release delivery
      uses: svenstaro/upload-release-action@v2
      with:
        repo_token: ${{ secrets.GITHUB_TOKEN }}
        file: ./Doppler.REST/bin/Release/net5.0/linux-x64/publish/*
        asset_name: Doppler Linux
        tag: ${{ github.ref }}
        overwrite: true
        body: "Doppler Linux release"
        file_glob: true