name: .NET

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 5.0.x
    - name: Restore dependencies
      run: dotnet restore
    - name: Build
      run: dotnet build --no-restore
    - name: Test
      run: dotnet test --no-build --verbosity normal
    - name: Publish linux web app
      working-directory: ./Doppler.REST
      run: dotnet publish -c Release --runtime linux-x64 --self-contained true
    - name: Publish windows web app
      working-directory: ./Doppler.REST
      run: dotnet publish -c Release --runtime win-x64 --self-contained true
    - name: Publish osx web app
      working-directory: ./Doppler.REST
      run: dotnet publish -c Release --runtime osx-x64 --self-contained true
    - name: Archive linux publish
      uses: thedoctor0/zip-release@master
      with:
        filename: 'publish-linux.tar.gz'
        path: ./Doppler.REST/bin/Release/net5.0/linux-x64/publish/
    - name: Archive windows publish
      uses: thedoctor0/zip-release@master
      with:
        filename: 'publish-windows.tar.gz'
        path: ./Doppler.REST/bin/Release/net5.0/win-x64/publish/
    - name: Archive osx publish
      uses: thedoctor0/zip-release@master
      with:
        filename: 'publish-osx.tar.gz'
        path: ./Doppler.REST/bin/Release/net5.0/osx-x64/publish/
    - name: Release linux delivery
      uses: svenstaro/upload-release-action@v2
      with:
        repo_token: ${{ secrets.GITHUB_TOKEN }}
        file: publish-linux.tar.gz
        asset_name: Doppler
        tag: ${{ github.ref }}
        overwrite: true
        body: "Doppler Linux release"
        file_glob: true
    - name: Release windows delivery
      uses: svenstaro/upload-release-action@v2
      with:
        repo_token: ${{ secrets.GITHUB_TOKEN }}
        file: publish-windows.tar.gz
        asset_name: Doppler
        tag: ${{ github.ref }}
        overwrite: true
        body: "Doppler Windows release"
        file_glob: true
    - name: Release osx delivery
      uses: svenstaro/upload-release-action@v2
      with:
        repo_token: ${{ secrets.GITHUB_TOKEN }}
        file: publish-osx.tar.gz
        asset_name: Doppler
        tag: ${{ github.ref }}
        overwrite: true
        body: "Doppler OSX release"
        file_glob: true